### ISSUE TITLE
sparql documentation: missing fields

### ISSUE THREAD

**Issue by floreverk** [CoGhent/CoGhent.github.io#7]
op volgende velden kunnen we nog niet queryen:
- iconografie onderwerp: een fout in de mapping (Entiteit.beeldtUit moet MensgemaaktObject.beeldtUit zijn).
- iconografie persoon: een fout in de mapping (Entiteit.beeldtUit moet MensgemaaktObject.beeldtUit zijn).
- vervaardiger rol: De volledige URI moet uitgeschreven worden bij values van @id, waardoor de triple niet doorkomt. 

+ value ontbreekt of geen SPARQL property te vinden bij volgende velden: Collectie, afmeting.waarde, afmeting.eenheid, verwerving.datum

**Comment by oliviervd** [comment]
ik pas het aan!
